#! /usr/bin/python
import sys
import operator 

def calc(input):
    if len(input) == 3:
        operator_input = input[1]
        operator_list = {
        '+': operator.__add__,
        '-': operator.__sub__,
        '*': operator.__mul__,
        '/': operator.__div__
        } 
        def calculate_result(operator_input):
            try:
                first_operand = int(input[0])
                third_operand = int(input[2])
                apply_operator = operator_list[operator_input]
                answer = apply_operator(first_operand, third_operand)
                print(answer)
            except:
                print('please give me integers')
        def calculate_division_result(operator_input):
            try:
                first_operand = float(input[0])
                third_operand = float(input[2])
                apply_operator = operator_list[operator_input]
                answer = apply_operator(first_operand, third_operand)
                print(answer)
            except:
                print('please give me integers or floats, thank you!')    
        if operator_input == '/':
            calculate_division_result(operator_input)
        elif operator_input:
            calculate_result(operator_input)
        else:
            print('I can perform addition, subtraction, multiplication or division')
    else:
        print('Sorry, I don\'t understand! Why don\'t you try 2 + 2?')

keep_running = True
while keep_running:
    user_input = raw_input('calc ')
    if user_input == 'exit':
        keep_running = False
    else:
        input = user_input.split(' ')
        calc(input)

# Helpful documentation:
# https://stackoverflow.com/questions/2983139/assign-operator-to-variable-in-python
