#! /usr/bin/python
import sys

file_name = sys.argv[1]
file = open(file_name, 'r')
for line in file:
    print(line),
file.close()

# obtain file name from parameter
# open file
# loop - read character (or line?) and print to the terminal
# loop ends when no more characters left
# close the file
# function ends 