#! /usr/bin/python
import sys
import socket

if len(sys.argv) == 2:
    port = int(sys.argv[1])
    s = socket.socket()
    s.bind(('0.0.0.0', port))
    s.listen(1)
    connection, address = s.accept()
    while True:
        data = connection.recv(1024)
        if not data: 
            break
        connection.sendall(data)
    connection.close()
else:
    print('please give me something like `anetecho 5000`')

# instructions:
# terminal 1 $ ./anetecho 5000
# terminal 2 $ nc localhost 5000