#! /usr/bin/python
import sys
import socket

if len(sys.argv) == 2:
    port = int(sys.argv[1])
    s = socket.socket()
    s.bind(('0.0.0.0', port))
    s.listen(1)
    connection, address = s.accept()
    while True:
        data = connection.recv(1024)
        if not data: 
            break
        connection.sendall(data)
    connection.close()
else:
    print('please give me something like `./anetechocalc 5000`')

# Pseudo code to add acalc to this:
# Inside the while block
# Take client's input
# Encode byte to string
# assign to acalc's input
# ACALC PROGRAMME
# assign acalc's output
# Decode string to byte
# print to STDOUT (as normal)
# https://stackoverflow.com/questions/606191/convert-bytes-to-a-string

# instructions:
# terminal 1 $ ./anetechocalc 5000
# terminal 2 $ nc localhost 5000